<?php
/* $Id$ */

/**************************************************
/	MicroID Module
/	Author: Tane Piper (digitalspaghetti@gmail.com)
/	URI: http://drupal.org/projects/microid
/	Author URI: http://digitalspaghetti.me.uk
/***************************************************/

/**
 * Display help and module information
 * @param section which section of the site we're displaying help 
 * @return help text for section
 */
function microid_help($section='') {
	$output = '';

	switch ($section) {
    	case "admin/help#microid":
      		$output = '<p>'.  t("This module creates a MicroID and embeds it in users posts."). '</p>';
      	break;
      	
      	case "admin/modules#description":
      		$output = '<p>'.  t("This module creates a MicroID and embeds it in users posts."). '</p>';
      	break;
  	}

  	return $output;
}

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the microid module
 */
function microid_perm() {
  return array('access content');
}


/***
 * function microid_genhash($email, $url)
 * This function generates the hash from
 * The users email and profile_homepage
 ***/

function microid_genhash($email, $url)
{
	return sha1(sha1("mailto:" . trim($email)) . sha1(trim($url)));
}

/***
 * function microid_nodeapi(&$node, $op, $teaser = NULL, $page = NULL)
 * Thanks to robrechtj on #drupal-support for helping me figure out
 * a few things on here!
 ***/

function microid_nodeapi(&$node, $op, $teaser = NULL, $page = NULL){
 	switch($op) {
 	 	case 'load':
 	 		$author = user_load(array('uid' => $node->uid));
 	 		return array('user_email' => $author->email, 'user_homepage' => $author->profile_homepage); 	 		
 	 	break;
 	 	case 'view':
 	 	
 	 		$hash = microid_genhash($node->user_email, $node->user_homepage);
 	 		
		  	if ($page && !$teaser) {
			   drupal_set_html_head('<meta name="microid" content="' . $hash . '" />');
			}
						
			drupal_add_js('$(function(){$("div[@id*=node]").addClass("microid-' . $hash . '")});', 'inline');
					
		break;
	}
}