<?php
/* $Id$ */

/**************************************************
/	MicroID Module
/	Author: Tane Piper (digitalspaghetti@gmail.com)
/	URI: http://drupal.org/projects/microid
/	Author URI: http://digitalspaghetti.me.uk
/***************************************************/

/**
 * Display help and module information
 * @param section which section of the site we're displaying help 
 * @return help text for section
 */
function microid_help($section='') {
	$output = '';

	switch ($section) {
    	case "admin/help#microid":
      		$output = '<p>'.  t("This module creates a MicroID and embeds it in users posts."). '</p>';
      	break;
      	
      	case "admin/modules#description":
      		$output = '<p>'.  t("This module creates a MicroID and embeds it in users posts."). '</p>';
      	break;
  	}

  	return $output;
} // function microid_help

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the microid module
 */
function microid_perm() {
  return array('access content');
} // function onthisdate_perm()

/**
 * Function to take action on user actions
 *
 */

function microid_user($type, &$edit, &$user, $category = NULL) {
	switch($type) {
		case 'update':
			return microid_update_profile($edit,$user, $category);
	 
	} 
}

/***
 * function microid_genhash($email, $url)
 * This function generates the hash from
 * The users email and profile_homepage
 ***/

function microid_genhash($email, $url)
{
	return sha1(sha1("mailto:" . trim($email)) . sha1(trim($url)));
}

/***
 * function microid_update_profile(&$edit,&$user, $category)
 * This function is when the user updates their profile
 ***/

function microid_update_profile(&$edit,&$user, $category) {
	$useremail =  $user->email;
	$useruri = $edit['profile_homepage'];
	
	$hash = microid_genhash($useremail, $useruri);
	
	$get_fid = "SELECT fid FROM {profile_fields} WHERE name = 'profile_microid'";
	$result = db_query($get_fid);
	$field_id = db_result($result);
	
	db_query("INSERT INTO {profile_values} (fid, uid, value) VALUES (%d, %d, '%s')", $field_id, $user->uid, $hash);
}

/***
 * function microid_nodeapi(&$node, $op, $teaser = NULL, $page = NULL)
 * Thanks to robrechtj on #drupal-support for helping me figure out
 * a few things on here!
 ***/

function microid_nodeapi(&$node, $op, $teaser = NULL, $page = NULL){
 	switch($op) {
 	 	case 'load':
 	 		$author = user_load(array('uid' => $node->uid));
 	 		return array('microid' => $author->profile_microid);
 	 	break;
 	 	case 'view':
		  	if ($page && !$teaser) {
			   drupal_set_html_head('<meta name="microid" content="' . $node->microid . '" />');
			}
			
			// Below code is not working 01/12/06 - If you can see whats wrong to patch it
			// please feel free to add to project issues.
			
			if ($teaser) {
				$node->teaser = '<span class="microid-' . $node->microid . '">' . $node->teaser . '</span>'; 	
			} else {
				$node->body = '<span class="microid-' . $node->microid . '">' . $node->body . '</span>';
			}		
		break;
	}
}